version: "3.8"
services:
  worker1:
    build: ./worker
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      PORT: 3001
    restart: on-failure
    volumes:
      - ./worker:/worker
  worker2:
    build: ./worker
    ports:
      - "3002:3002"
    env_file: .env
    environment:
      PORT: 3002
    restart: on-failure
    volumes:
      - ./worker:/worker
  worker3:
    build: ./worker
    ports:
      - "3003:3003"
    env_file: .env
    environment:
      PORT: 3003
    restart: on-failure
    volumes:
      - ./worker:/worker
